// <auto-generated />
namespace Settimana_19_Esercizio_Unico.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class NuovaColonnaDataInOrdini : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NuovaColonnaDataInOrdini));
        
        string IMigrationMetadata.Id
        {
            get { return "202403151325264_NuovaColonnaDataInOrdini"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
